apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
  labels:
    app: backend
  name: backend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'backend:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: src/geo-ws-rand/
    git:
      ref: master
      uri: 'http://gitlab.rete.poste/SFORZAPI/demo1-jenkins-app-a.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nodejs:10'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: X-bqiX1YBgbRpElL9tRJ
      type: GitHub
    - generic:
        secret: S4O4JJelZCqcZu06sqvf
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: >-
          docker-registry.default.svc:5000/openshift/nodejs@sha256:74a3ef2964efc03dfc239da3f09691b720ce54ff4bb47588864adb222133f0fc
      type: ImageChange
