apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
  labels:
    app: frontend-data-platform-patterns
  name: frontend-data-platform-patterns
  namespace: data-plaform-cqrs
spec:
  lookupPolicy:
    local: false
