apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
  labels:
    app: frontend
  name: frontend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'frontend:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: src/geo-portal/
    git:
      uri: 'https://github.com/mauiroma/geo.git'
      ref: master
    type: Git
  strategy:
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
