apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: 'true'
  creationTimestamp: '2020-03-04T00:04:50Z'
  labels:
    app: acme-helloworld
  name: acme-helloworld
  namespace: newsletter-d3js
  resourceVersion: '43090956'
  selfLink: >-
    /apis/route.openshift.io/v1/namespaces/newsletter-d3js/routes/acme-helloworld
  uid: c48b90c3-5dab-11ea-a282-00505683119b
spec:
  host: acme-helloworld-newsletter-d3js.app.svil2.ocprm.testposte
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: acme-helloworld
    weight: 100
  wildcardPolicy: None
status:
  ingress:
    - conditions:
        - lastTransitionTime: '2020-03-04T00:04:50Z'
          status: 'True'
          type: Admitted
      host: acme-helloworld-newsletter-d3js.app.svil2.ocprm.testposte
      routerName: router
      wildcardPolicy: None

